require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - '**/config.ru'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/admin/**/*'
    - 'app/helpers/**/*'
    - 'app/policies/**/*'
Rails:
  Enabled: true
Rails/InverseOf:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
  Exclude:
    - 'app/services/tasks/manage_event_schedule.rb'
Rails/DynamicFindBy:
  Enabled: false
Documentation:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
Style/StringConcatenation:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/NonDeterministicRequireOrder:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/factories/**'
Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
    - 'app/services/discord/base.rb'
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false

Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*'
    - 'config/routes.rb'
  Max: 33
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/ParameterLists:
  Max: 10
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*_helper.rb'
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 12
Naming/VariableNumber:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
RSpec/ExampleLength:
  Max: 50
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/helpers/**/*'
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
    - 'spec/scenarios/**/*'
Style/DateTime:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RegexpLiteral:
  StyleGuide: slashes
Style/GuardClause:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/StringLiterals:
  EnforcedStyle: single_quotes

